### ISSUE TITLE
Put tests in separate module

### ISSUE THREAD

**Issue by ljharb** [tc39/Array.prototype.includes#30]
What would you think about putting the tests in a separate module?

I'm about to release an ES3-compatible `Array#includes` polyfill, and while I've got my own tests, I'd love to run yours against my module. Currently, I tried installing this module as a devDep, and running `npm explore array.prototype.includes -- 'npm install && npm test'` which only works if I modify your package.json to reference my prelude.

If the tests are a separate module, then both of us could require it and run it against our own shimmed environments. Thoughts?

**Comment by rwaldron** [comment]
Also: tests in separate repo can more readily be moved to test262 :D

**Comment by domenic** [comment]
The tests are already PRed against test262 (tc39/test262#95). If anything, that is the separate module they should belong in.

But you can just install this as a devDep and use your own test command, right?

```
test262-harness --prelude=index.js --runner=node node_modules/array.prototype.includes/test/built-ins/Array/prototype/includes/*.js
```

**Comment by ljharb** [comment]
That's true, I can - my preference is to not have to couple my module tightly to the way tests are run, and I really don't like delving through `node_modules` manually.

At any rate, test262 can't be a replacement for my own tests (for any shims or polyfills) until they can run in ES3 / node 0.6, so this might not be worth investigating at all at this time, due to "let" usage and things of that nature.

**Comment by domenic** [comment]
Yeah, it's a non-goal of this test suite to run in ES3.

**Comment by ljharb** [comment]
That means it's a non-goal to get `es5-shim`, `es6-shim`, and most every polyfill in the ecosystem to run `test262` :-(
I'll keep that in mind for the future, thanks.

**Comment by rwaldron** [comment]
> The tests are already PRed against test262

Awesome. I was mobile and didn't really think to look there.

**Comment by bterlson** [comment]
> Yeah, it's a non-goal of this test suite to run in ES3.

@Domenic I agree, but to be clear for @ljharb / @rwaldron / the record:

1. It is a non-goal for test262 to verify ES3 semantics. Where ES-latest and ES3 semantics differ, test262 will only validate the former and never the latter.
2. It is a non-goal for test262 tests to stick to ES3 semantics except for the feature under test. This is because integration tests between different ES5/ES6 features are very important to test. For example, a test for `[obj].includes(new Proxy(obj, {}));` is quite reasonable. However:

    a. Test262 tests should use the simplest (ES3) language features unless they are explicitly testing interactions between more advanced features. For example, tests should not use forEach when a for loop will do.
    b. Test262 tests should flag dependencies on advanced language features in the frontmatter so harnesses can avoid such tests. There is a proposal for this that I will be formalizing soon, but the gist is a "features" key in the frontmatter that is an array of feature names.
    c. Test262-harness users can use a config.js file to exclude any number of tests which should work in the meantime to exclude tests that have no hope of running in an ES3 environment. This should work today against node 0.6 afaik.

There may be specific issues with these tests or this polyfill in an ES3 environment but generally it is a very important goal of test262 to work for shims and such, and I think it will modulo some harness improvements to ease running in browser and potentially selecting the proper tests for an ESx environment. @ljharb do you see differently?

**Comment by rwaldron** [comment]
This makes sense to me, but I was already on-board after @domenic mentioned it above.

**Comment by ljharb** [comment]
@bterlson Thanks for the clarification - based on those philosophies I think we're still on the right track to have test-262 replace all the tests in the `es5-shim`, `es6-shim`, (upcoming) `es7-shim`, as well as many tens of individual shims/polyfills :-)
